name: PS2_Build
on: [push]
jobs:
  build-volkov:
    runs-on: ubuntu-latest
    container: ps2dev/ps2sdk:latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Project
        run: |
          # Frissítjük a csomagokat, hogy legyen 'make'
          apk add --no-cache make gcc build-base git
          
          # Letöltjük a gsKit-et egy fix, működő paranccsal
          git clone --depth 1 https://github.com
          cd gsKit
          ./build.sh install
          cd ..
          
          # Most futtatjuk a te programod fordítását
          make
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: volkov-commander-ps2
          path: volkov.elf

