name: PS2_Build
on: [push]
jobs:
  build-volkov:
    runs-on: ubuntu-latest
    container: ps2dev/ps2sdk:latest
    steps:
      - uses: actions/checkout@v4
      - name: Build gsKit and App
        run: |
          apk add --no-cache git make gcc build-base bash
          # FIGYELEM: Itt a teljes URL-nek kell lennie!
          git clone https://github.com
          cd gsKit
          ./build.sh install
          cd ..
          # Most futtatjuk a te programod fordítását
          make
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: volkov-commander-ps2
          path: volkov.elf
