name: PS2_Build
on: [push]
jobs:
  build-volkov:
    runs-on: ubuntu-latest
    container: ps2dev/ps2sdk:latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Project
        run: |
          apk add --no-cache git make gcc build-base
          
          # Trükk: Változóba tesszük a linket, hogy ne vágja le
          export GSKIT_URL="https://github.com"
          git clone --depth 1 $GSKIT_URL
          
          cd gsKit
          ./build.sh install
          cd ..
          
          make
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: volkov-commander-ps2
          path: volkov.elf
